### ISSUE TITLE
使用secretnote链接scql的时候，报 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by etanwaontson** [secretflow/secretnote#50]
![image](https://github.com/secretflow/secretnote/assets/175196180/a443760f-ab8e-49a8-9b11-bcdadf5396cb)

**Comment by etanwaontson** [comment]
访问到broker的时候，接口是404
![image](https://github.com/user-attachments/assets/28cc5ad1-d9d5-44f2-b6e7-4a6bb2f1d38d)

**Comment by etanwaontson** [comment]
我的broker的配置，麻烦大佬帮忙看下
```
intra_server:
  host: 0.0.0.0
  port: 50050
inter_server:
  port: 50051
log_level: debug
party_code: alice
session_expire_time: 24h
session_expire_check_time: 1m
party_info_file: "/home/admin/configs/party_info.json"
private_key_path: "/home/admin/configs/ed25519key.pem"
intra_host: broker:50050
engine:
  timeout: 120s
  protocol: http
  content_type: application/json
  uris:
    - for_peer: http://xx.xxx.xxx.xxx
      for_self: engine:50052
storage:
  type: mysql
  conn_str: "root:xxxxx@tcp(xxx.xxx.xxx.xxx:xxxx)/scql_broker_alice?charset=utf8mb4&parseTime=True&loc=Local&interpolateParams=true"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
```

**Comment by zimu-yuxi** [comment]
for_peer不要http，使用ip+port

**Comment by etanwaontson** [comment]
还是不行，我贴一下我完成的配置
config.yml
```
intra_server:
  port: 8080
inter_server:
  host: 0.0.0.0
  port: 8081
log_level: debug
party_code: alice
session_expire_time: 24h
session_expire_check_time: 1m
party_info_file: "/home/admin/configs/party_info.json"
private_key_path: "/home/admin/configs/ed25519key.pem"
intra_host: broker:8080
engine:
  timeout: 120s
  protocol: http
  content_type: application/json
  uris:
    - for_peer: 10.177.85.157:8083
      for_self: engine:8083
storage:
  type: mysql
  conn_str: "username:password@tcp(ip:port)/scql_broker_alice?charset=utf8mb4&parseTime=True&loc=Local&interpolateParams=true"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
```
gflags.conf
```
--listen_port=8003
--datasource_router=embed
--enable_driver_authorization=false
--server_enable_ssl=false
--driver_enable_ssl_as_client=false
--peer_engine_enable_ssl_as_client=false
--embed_router_conf={"datasources":[{"id":"ds001","name":"mysql db","kind":"MYSQL","connection_str":"db=scql_engine_alice;user=;password=;host=ip:port;auto-reconnect=true"}],"rules":[{"db":"*","table":"*","datasource_id":"ds001"}]}
# party authentication flags
--enable_self_auth=false
```
docker-compose.yaml
```
version: '3.8'
services:
  broker:
    image: secretflow/scql:stable
    command:
      - /home/admin/bin/broker
      - -config=/home/admin/configs/config.yml
    restart: always
    ports:
      - 50054:8080
      - 50051:8081
    volumes:
      - ./config.yml:/home/admin/configs/config.yml
      - ./party_info.json:/home/admin/configs/party_info.json
      - ./ed25519key.pem:/home/admin/configs/ed25519key.pem
  engine:
    cap_add:
      - NET_ADMIN
    command:
      - /home/admin/bin/scqlengine
      - --flagfile=/home/admin/engine/conf/gflags.conf
    image: secretflow/scql:stable
    ports:
      - 50052:8083
    volumes:
      - ./gflags.conf:/home/admin/engine/conf/gflags.conf
    ```
part.json
```
{
  "participants": [
    {
      "party_code": "alice",
      "endpoint": "10.177.85.157:50051",
      "pubkey": ""
    },
    {
      "party_code": "bob",
      "endpoint": "10.177.85.158.50051",
      "pubkey": ""
    }
  ]
}
```
